### ISSUE TITLE
mailto: Links not working on /terms/ and /privacy/ pages on production

### ISSUE THREAD

**Issue by brev** [numenta/numenta-web#11]
`mailto:` Links not working on `/terms/` and `/privacy/` pages on production.
Just takes you to top of page, doesn't trigger mail client to open.

Weird, because they work fine on staging: http://staging.numenta.com/legal/terms/.
That's the exact same code, just different server. 

No errors or anything else to guide. Tested on Chrome Latest Stable (as of today), Mac OS/X.

### Steps to Reproduce

* Visit these URLs:
  * http://numenta.com/legal/terms/
  * http://numenta.com/legal/privacy/
* Scroll to bottom of page
* Click on links to email addresses
* See browser scrolls to top instead

cc @jsfowles

**Comment by jsfowles** [comment]
Verified this isn't working on Mobile with Safari and Chrome. Desktop testing done with Edge, Safari, Chrome, and Mozilla and mailto: links still scrolling to top of page.

**Comment by brev** [comment]
@jsfowles I have no idea on this one still, if you can find any info, or come up with any ideas, thanks!

**Comment by brev** [comment]
Duplicates https://jira.numenta.com/browse/WEB-319 (Apply Now button also not working on Careers, which is P1, I'll work on in JIRA on hours).

**Comment by brev** [comment]
https://github.com/substack/catch-links/pull/7

**Comment by strongSoda** [comment]
It works by adding target = "_top"
