### ISSUE TITLE
Sync FAQ sections on site

### ISSUE THREAD

**Issue by brev** [numenta/numenta-web#14]
There are couple different FAQ sections on the site:
1. Built: http://numenta.com/business-strategy-and-ip/#faq
   - Source: https://github.com/numenta/numenta-web/blob/master/numenta.com/pages/business-strategy-and-ip/_Section.jsx#L258-L314
     - This one uses HTML definition lists (`<dl>`, `<dt>`, `<dd>`) 
2. Built: http://numenta.com/htm-studio/#faq
   - Source: https://github.com/numenta/numenta-web/blob/master/numenta.com/pages/htm-studio/index.jsx#L128-L141
     - This one is just `<div>`s.  Visually, on desktop widths, there is unwanted padding on the left of each FAQ answer/definition.

These should match in style, markup, etc.  Maybe some refactoring.

See related issue: https://github.com/numenta/numenta-web/issues/15

cc @jsfowles

**Comment by jsfowles** [comment]
@brev - Can I work on this now or does #15 need to be completed first?

**Comment by brev** [comment]
This can be done separately first, although I probably need to define it better, let me get back to you on requirements.

**Comment by brev** [comment]
ok @jsfowles go ahead

**Comment by brev** [comment]
meh.
