### ISSUE TITLE
Add our new site to "List of sites created with Gatsby" on their repo

### ISSUE THREAD

**Issue by brev** [numenta/numenta-web#25]
Add new http://numenta.com to this list:
  https://github.com/gatsbyjs/gatsby#sites-built-with-gatsby

I'd also suggest asking them if it'd be OK to move that list to their wiki:
  https://github.com/gatsbyjs/gatsby/wiki
And then, link to the new wiki page from the README.

@jsfowles this is a nice easy one

**Comment by jsfowles** [comment]
Numenta.com is up on Gatsby's 'built with' README.

Owner mentioned that the 'built with' list is getting long and they plan is to build a site for Gatsby soonish and at that point most of the README will be moved there.
