### ISSUE TITLE
Automatic link icons?

### ISSUE THREAD

**Issue by brev** [numenta/numenta-web#31]
Could add little icons to all text links automatically and simple in CSS. Perhaps a note for external link or PDF link etc.

Originally: https://jira.numenta.com/browse/WEB-112

cc @jsfowles

**Comment by jsfowles** [comment]
Are you thinking something similar to this:

https://lefkomedia.com/adding-external-link-indicator-with-css/

**Comment by brev** [comment]
@jsfowles yup exactly, although not selecting on `_target`, maybe on `href` that isn't `numenta.com` or a class name or something.

**Comment by brev** [comment]
Finished for new/upcoming **Numenta.org** here:
* https://jira.numenta.com/browse/WEB-387
* https://jira.numenta.com/browse/WEB-393

Need to clone this over to **Numenta.com** if marketing approves.

**Comment by brev** [comment]
this is working a bit on staging.numenta.org, can be used as needed.
