### ISSUE TITLE
Pseudocode does not contain line numbers but there are references in the text to specific lines of the pseudocode

### ISSUE THREAD

**Issue by nbro** [numenta/numenta-web#564]
In this article [https://numenta.com/resources/biological-and-machine-intelligence/spatial-pooling-algorithm/](https://numenta.com/resources/biological-and-machine-intelligence/spatial-pooling-algorithm/), whose content is written in [https://github.com/numenta/numenta-web/blob/master/packages/numenta.com/pages/resources/biological-and-machine-intelligence/spatial-pooling-algorithm/index.jsx](https://github.com/numenta/numenta-web/blob/master/packages/numenta.com/pages/resources/biological-and-machine-intelligence/spatial-pooling-algorithm/index.jsx), you refer to lines of the pseudocode, but the pieces of code of that article do not contain line numbers, which makes it difficult to follow the article at those points.

**Comment by rhyolight** [comment]
Thanks @nbro. We are in the process of removing that page. The original content at https://numenta.com/assets/pdf/spatial-pooling-algorithm/Spatial-Pooling-Algorithm-Details.pdf is better. The HTML was an experiment, and now I am continuing work that would be in BAMI on https://buildinghtm.systems.

**Comment by nbro** [comment]
@rhyolight I started reading the BAMI book. Even though I only read the first two chapters, I can already say that the book is quite accessible and understandable, but it's incomplete. (Maybe it also lacks a few details and some statements are not explained, and maybe they could and should.)

Wouldn't it be better to, instead of starting new info-sharing projects, try to write the chapters of the BAMI that can already be written (and improve or complete the existing ones)? For example, there's a plan to write a chapter on HTM neurons, but it still doesn't exist. That chapter could and, IMHO, should already exist. 

Furthermore, maybe the community could also contribute to the writing of this book? Of course, the chapters or parts of it written by community members could and should be reviewed by Numenta researchers, in particular, by the experts in the corresponding field or topic.

Finally, I think it would be more "scientific" to use Latex (instead of word), to write this document (even though this is a little subjective and just a detail)?
