### ISSUE TITLE
Source files need copyright notice at top of each

### ISSUE THREAD

**Issue by brev** [numenta/numenta-web#8]
Top of each source file (`.js`, `.jsx`, `.css`, off the top of my head) needs copyright notice.

Top of this file is an example:
https://github.com/numenta/numenta-web/blob/master/numenta.com/pages/index.jsx

Please check http://npmjs.com, I believe there should be tools to automate this. If not, you could make your own. Or, if that feels daunting, the old fashioned slow brute force method works too. :)

@jsfowles feel free to take this one!

**Comment by brev** [comment]
@jsfowles just add a comment with my name (@brev) if you need any help here.

**Comment by jsfowles** [comment]
Fixed with pull #23

**Comment by brev** [comment]
@jsfowles how about files under `/pages`?  And a few scattered `.js` files too.

**Comment by jsfowles** [comment]
Accidental close. Further copyright for /pages and randoms .js files

**Comment by jsfowles** [comment]
Officially fixed with pull #27 & #23. Closing out.

**Comment by jsfowles** [comment]
Officially fixed with pull #27 & #23. Closing out.
